import { Link, useNavigate } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { useAuthStore } from '@/stores/authStore';
import { Zap, ArrowRight, Layers, BarChart3, Sparkles, GripVertical } from 'lucide-react';

export default function LandingPage() {
  const { isAuthenticated } = useAuthStore();
  const navigate = useNavigate();

  const features = [
    {
      icon: GripVertical,
      title: 'Conversational First',
      description: 'Ditch static forms. Engage users with a dynamic chat interface that adapts to their answers.',
    },
    {
      icon: Sparkles,
      title: 'AI Intelligence',
      description: 'FormMorph understands natural language, asks follow-up questions, and classifies sentiments automatically.',
    },
    {
      icon: BarChart3,
      title: 'Deep Analytics',
      description: 'Get instant Executive Summaries, response clustering, and anomaly detection generated by AI.',
    },
    {
      icon: Layers,
      title: 'Embed Anywhere',
      description: 'Publish your conversational form via a simple link or embed it directly into your site as a chat widget.',
    },
  ];

  return (
    <div className="min-h-screen animated-gradient">
      {/* Nav */}
      <nav className="flex items-center justify-between px-6 py-4 max-w-7xl mx-auto">
        <div className="flex items-center gap-2">
          <Zap className="h-7 w-7 text-indigo-500" />
          <span className="text-xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-indigo-400 via-purple-400 to-pink-400">FormMorph</span>
        </div>
        <div className="flex items-center gap-3">
          {isAuthenticated ? (
            <Button onClick={() => navigate('/dashboard')}>Dashboard</Button>
          ) : (
            <>
              <Button variant="ghost" asChild>
                <Link to="/login">Sign In</Link>
              </Button>
              <Button asChild>
                <Link to="/register">Get Started</Link>
              </Button>
            </>
          )}
        </div>
      </nav>

      {/* Hero */}
      <section className="max-w-7xl mx-auto px-6 pt-20 pb-32 text-center">
        <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-indigo-500/10 border border-indigo-500/20 text-indigo-400 text-sm font-medium mb-6 animate-float">
          <Sparkles className="h-4 w-4" />
          The Conversational AI Form Engine
        </div>
        <h1 className="text-5xl md:text-7xl lg:text-8xl font-black tracking-tight mb-6 leading-tight">
          Forms that feel like <br />
          <span className="bg-clip-text text-transparent bg-gradient-to-r from-indigo-400 via-purple-400 to-pink-400 animate-pulse">
            a conversation.
          </span>
        </h1>
        <p className="text-lg md:text-xl text-muted-foreground max-w-2xl mx-auto mb-10 leading-relaxed">
          Traditional forms are static and boring. FormMorph turns data collection into a 
          dynamic chat — questions change based on answers, AI interprets responses, and 
          you get intelligent insights instantly.
        </p>
        <div className="flex items-center justify-center gap-4">
          <Button size="lg" className="text-base px-8 bg-indigo-600 hover:bg-indigo-700 text-white border-none shadow-[0_0_20px_rgba(79,70,229,0.4)]" asChild>
            <Link to="/register">
              Start building <ArrowRight className="ml-2 h-4 w-4" />
            </Link>
          </Button>
          <Button size="lg" variant="outline" className="text-base px-8 border-indigo-500/30 hover:bg-indigo-500/10" asChild>
            <Link to="/login">Sign In</Link>
          </Button>
        </div>
      </section>

      {/* Features */}
      <section className="max-w-7xl mx-auto px-6 pb-32">
        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
          {features.map((feature) => (
            <div
              key={feature.title}
              className="group p-6 rounded-xl glass border-white/5 hover:border-primary/30 transition-all duration-300 hover:-translate-y-1"
            >
              <div className="h-12 w-12 rounded-lg bg-primary/10 flex items-center justify-center mb-4 group-hover:bg-primary/20 transition-colors">
                <feature.icon className="h-6 w-6 text-primary" />
              </div>
              <h3 className="text-lg font-semibold mb-2">{feature.title}</h3>
              <p className="text-sm text-muted-foreground">{feature.description}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-white/5 py-8">
        <div className="max-w-7xl mx-auto px-6 text-center text-sm text-muted-foreground">
          <p>© 2026 FormMorph. Built for the 24hr Hackathon.</p>
        </div>
      </footer>
    </div>
  );
}
